"""empty message

Revision ID: 75939f703cfe
Revises: 3b52da6cecd7
Create Date: 2021-10-12 18:11:55.145196

"""
from alembic import op
import sqlalchemy as sa


import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '75939f703cfe'
down_revision = '3b52da6cecd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instructions', 'directions')
    op.drop_column('media', 'mediaUrl')
    if environment == "production":
        op.execute(f"ALTER TABLE instructions SET SCHEMA {SCHEMA};")
        op.execute(f"ALTER TABLE media SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('mediaUrl', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('instructions', sa.Column('directions', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
